name: Build & Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200-preview-014883
    - name: Build marketing API
      run: dotnet build src/Services/Marketing/Marketing.Api/Marketing.Api.csproj --configuration Release
    - name: Build outgoing communications API
      run: dotnet build src/Services/OutgoingCommunications/OutgoingCommunications.Api/OutgoingCommunications.Api.csproj --configuration Release
    - name: Build website
      run: dotnet build src/Web/WebMvc/WebMvc.csproj
    - name: Run marketing API unit tests
      run: dotnet test src/Services/Marketing/Marketing.UnitTests/Marketing.UnitTests.csproj --configuration Release

  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
