name: Code quality analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Display message, start the code quality analysis with Sonar
      run: echo Start code analysis
    - name: Run Sonar Cloud analysis
      uses: SonarSource/sonarcloud-github-action@v1.1
    - name: Display message, end the code quality analysis with Sonar
      run: echo Code analysis ended
